---
title: "Objects for input data to and results from nature index calculations"
subtitle: "No subtitle yet"
author: "Bård Pedersen, Stein Are Sæther, Jens Åström"
date: "Norwegian Institute for Nature Research, February 26, 2017"
output: pdf_document
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This document explains the structure and content of objects storing the input data to a calculation of the nature index. It also describes objects resulting from the calculation. It starts with an overview of the information required as input to a nature index calculation.

# Input data

In order to calculate the nature index it is necessary to provide information about each indicator involved, all indicator observations and reference values, all indicator areas, basic spatial units and NI-areas 

## Indicators

## Indicator abservations

## Reference values

## Basic spatial units

## Indicator areas

## NI-areas

In order to use the above functions to calculate NI for a set of $N.reg$ NI-areas, from a set of in total $N.obs$ indicator observations and reference values, over $N.years$ years, for $N.ind$ indicators from altogether $N.omr = N.obs/(N.years+1)$ indicator areas involving $N.kom$ basic spatial units, the following input data should be provided:

1. A data frame with indicator observations **together** with reference values
2. A data frame with indicator data
3. A data frame with basic spatial unit data
4. A data frame relating indicator areas to indicators
5. A data frame descrbing indicator areas in terms of basic spatial units

## Indicator observations and reference values

The data frame should contain at least the following variables (variable names may be different)

Variable | Type | Explanation
:----------------- | :-------------: | :---------------------------------------------
ValueID | integer | vector of indicator observation- and reference value IDs
Expected.value | double | vector of the indicator observations' and reference values' expected values
Lower	 | double  | vector of the observations' 0.25 (lower) quartiles
Upper	 | double | vector of the observations' 0.75 (upper) quartiles
IndicatorID | integer | vector of corresponding indicator IDs
IndicatorareaID | integer | vector of corresponding indicator area IDs
ReferenceYearID | integer | vector of corresponding IDs for observation years / reference values

Thus each indicator observation consists of the expected value together with the upper and lower quartiles. Each observation should have a unique ID and be linked to the correct indicator and indicator area through their IDs.

The last variable should signal whether the entry is a reference value or indicator observation. If it is an indicator observation the year or a yearID should be entered. If it is a reference value, an integer code, e.g. $0$, should be entered.

## Indicators

The data frame should contain at least the following variables (variable names may be changed)

Variable | Type | Explanation
:----------------- | :-------------: | :---------------------------------------------
IndicatorID | integer | vector of indicator IDs
Indicator_name | character | vector of the names of indicators
Scalingmodel | integer | vector of scaling model IDs, 1 = LOW and 2 = MAX
TrophicgroupID | integer | vector of trophic group IDs that the corresponding indicator belongs to
Key.indicators | logical | vector indicating whether corresponding indicator is a key indicator or not
Fidelity | double | vector of indicator fidelities to the major habitat in question

The data frame should contain complete data for all indicators included in the calculation.
The code for scaling models should be 1 for LOW and 2 for MAX.
Key indicators should be signalled with TRUE, non-key indicators with FALSE.
Fidelity should be gven as a number between 0 and 1.

## Basic spatial units and NI-areas

The data frame should contain at least the following variables (variable names may be changed)

Variable | Type | Explanation
:----------------- | :-------------: | :---------------------------------------------
Basicsunit | character | vector of names of basic spatial units
NIarea | character | vector of NI area names that the corresponding basic spatial units are part of
Area | double | vector containing the areas of basic spatial units

An NI-area consists of those basic spatial units that share the same name in the variable NIarea.
Basic spatial units may be grouped into NI-areas in several different ways by adding new "NIarea"-variables to the data frame

## To relate indicator areas to indicators

The data frame should contain the following variables (variable names may be changed)

Variable | Type | Explanation
:----------------- | :-------------: | :---------------------------------------------
IndicatorareaID | integer | vector of unique indicator area IDs
Indicator_name | character | vector of indicator names

All indicator areas that are defined for the same indicator should have identical entries in Indicator_name.

## To describe indicator areas in terms of basic spatial units

The data frame should contain at least the following variables (variable names may be changed)

Variable | Type | Explanation
:----------------- | :-------------: | :---------------------------------------------
IndicatorareaID | integer | vector of indicator area IDs
Basicsunit | character | vector of names of basic spatial units

The ID of an indicator area consisting of $n$ basic spatial units should be entered $n$ times in IndicatorareaID, while the names of the $n$ basic spatial units should be entered in the corresponding entries of Basicsunit.

\pagebreak


